serializer 초안 완성
noion0511/opencurtain pull request #2
Opened 2019-09-27 03:44 UTC by noion0511

2019-09-27 08:37 UTC, z-hoony commented on opencurtain/urls.py
> +router.register(r'departments', views.DepartmentsViewSet)
DepartmentsViewSet가 아니라 DepartmentViewSet 입니당

2019-09-27 09:09 UTC, noion0511 commented
#3

2019-09-27 11:31 UTC, z-hoony requested changes

2019-09-27 11:31 UTC, z-hoony commented on restserver/serializers.py
> +        fields = ['id','username', 'email', 'university']
list의 요소를 나열할 때 comma 뒤에는 공백을 추가하는게 보기 좋음
(예: ['id', 'username', 'email'])

2019-09-27 11:31 UTC, z-hoony commented on opencurtain/urls.py
> +router.register(r'comments',views.CommentViewSet)
함수의 인자를 나열할 때 comma 뒤에는 공백을 추가하는게 보기 좋음
(예: router.register("comments", views.CommentViewSet))

2019-09-27 11:31 UTC, z-hoony commented on restserver/models.py
> +#from django.db import models
설명이 아닌 코드 주석은 필요 없을 경우 삭제

2019-09-27 11:31 UTC, z-hoony commented on restserver/models.py
> +#from django.conf import settings
설명이 아닌 코드 주석은 필요 없을 경우 삭제

2019-09-27 11:31 UTC, z-hoony commented on restserver/serializers.py
> +        fields = ['id','board']
list의 요소를 나열할 때 comma 뒤에는 공백을 추가하는게 보기 좋음
(예: ['id', 'username', 'email'])

2019-09-27 11:31 UTC, z-hoony commented on restserver/serializers.py
> +        fields = ['id','boardname']
list의 요소를 나열할 때 comma 뒤에는 공백을 추가하는게 보기 좋음
(예: ['id', 'username', 'email'])

2019-09-27 11:31 UTC, z-hoony commented on restserver/serializers.py
> +        fields = ['id','university','board']
list의 요소를 나열할 때 comma 뒤에는 공백을 추가하는게 보기 좋음
(예: ['id', 'username', 'email'])

2019-09-27 11:31 UTC, z-hoony commented on restserver/serializers.py
>          model = Faculty
list의 요소를 나열할 때 comma 뒤에는 공백을 추가하는게 보기 좋음
(예: ['id', 'username', 'email'])

2019-09-27 11:31 UTC, z-hoony commented on restserver/serializers.py
> +        fields = ['id','departmentname','faculty','university','board']
list의 요소를 나열할 때 comma 뒤에는 공백을 추가하는게 보기 좋음
(예: ['id', 'username', 'email'])

2019-09-27 11:31 UTC, z-hoony commented on restserver/serializers.py
> +        fields = ['id','user','timestemp','title','content']
list의 요소를 나열할 때 comma 뒤에는 공백을 추가하는게 보기 좋음
(예: ['id', 'username', 'email'])

2019-09-27 11:31 UTC, z-hoony commented on restserver/serializers.py
> +        fields = ['user','timestemp','posts','comment']
list의 요소를 나열할 때 comma 뒤에는 공백을 추가하는게 보기 좋음
(예: ['id', 'username', 'email'])

2019-10-23 05:58 UTC, z-hoony commented
User 관련 기능은 다른 브랜치에서 작업하고 올려주세요
그리고 django-admin startapp을 이용해서 User 부분은 다른 앱으로 만들어서 분리시키는것이 좋아보입니다

2019-10-24 01:04 UTC, z-hoony commented
일단 머지 할테니 다른 브랜치로 작업하고 새로 pr 올려주세요

2019-10-24 01:05 UTC, merged